modLoader="scorge"
loaderVersion="[1,]"
#updateJSONURL="https://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json"
issueTrackerURL="https://github.com/MinecraftForge/Scorge/issues"
logoFile="forge_logo.png"
#must be a scala Object and not a class

[[mods]]
    modId="scorge"
    entryObject="net.minecraftforge.scorge.Scorge"
    displayName="Scorge"
    description='''
    The offical scala language loader for Forge.
    '''
    version="1.0.0"
